baseurl: ''
languageCode: en-us
title: Pagoda
googleAnalytics: ""
disqusShortname: ""
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: false
pygmentsUseClasses: false
minify: false
paginate: 9999
disableKinds:
  - section
  - categories
  - tags

permalinks:
  writing: /:year/:month/:day/:slug/

params:
  description: "experience inner transcendence on up to 64 cores"

frontmatter:
  author: Timo Sarkar
  github: 'https://github.com/0xtimosarkar/pagoda'
  facebook: ''
  og_image: 
  sitename: Pagoda
  twitter: ''

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed


