name: Hugo Build and Deploy

on:
  push:
    branches:
      - www

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
      
    - name: Build with Hugo
      if: contains(github.event.head_commit.message, 'BUILD')
      run: hugo
      
    - name: Deploy to GitHub Pages
      if: contains(github.event.head_commit.message, 'BUILD')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
