name: Hugo Build and Deploy

on:
  push:
    branches:
      - www

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
      
    - name: Install Surge CLI
      run: npm install -g surge

    - name: Install hugo
      if: contains(github.event.head_commit.message, 'BUILD')
      run: sudo apt-get install hugo
      
    - name: Build site   
      run: hugo
      
    - name: Deploy to Surge
      if: contains(github.event.head_commit.message, 'BUILD')
      run: surge public/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
